INSERT INTO Club (ClubID, ClubName, Country) VALUES (1, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (2, 'Juventus', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (3, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (4, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (5, 'Atlético Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (6, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (7, 'FC Bayern München', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (8, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (9, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (10, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (11, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (12, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (13, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (14, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (15, 'Chelsea', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (16, 'Tottenham Hotspur', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (17, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (18, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (19, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (20, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (21, 'FC Bayern München', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (22, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (23, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (24, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (25, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (26, 'Napoli', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (27, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (28, 'Manchester United', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (29, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (30, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (31, 'Arsenal', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (32, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (33, 'Inter', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (34, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (35, 'Juventus', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (36, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (37, 'FC Bayern München', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (38, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (39, 'Juventus', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (40, 'Tottenham Hotspur', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (41, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (42, 'Manchester United', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (43, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (44, 'Lazio', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (45, 'Inter', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (46, 'Valencia CF', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (47, 'Borussia Dortmund', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (48, 'Juventus', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (49, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (50, 'Inter', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (51, 'Borussia Dortmund', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (52, 'Napoli', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (53, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (54, 'Tottenham Hotspur', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (55, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (56, 'Borussia Dortmund', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (57, 'Inter', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (58, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (59, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (60, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (61, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (62, 'Manchester United', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (63, 'RB Leipzig', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (64, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (65, 'Leicester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (66, 'Ajax', 'Netherlands');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (67, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (68, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (69, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (70, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (71, 'Napoli', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (72, 'Atlético Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (73, 'Inter', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (74, 'FC Bayern München', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (75, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (76, 'Juventus', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (77, 'Tottenham Hotspur', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (78, 'Juventus', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (79, 'Paris Saint-Germain', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (80, 'Borussia Mönchengladbach', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (81, 'Atalanta', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (82, 'Juventus', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (83, 'Manchester City', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (84, 'Liverpool', 'England');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (85, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (86, 'Milan', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (87, 'Ajax', 'Netherlands');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (88, 'Lazio', 'Serbia'); 
INSERT INTO Club (ClubID, ClubName, Country) VALUES (89, 'Real Betis', 'France');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (90, 'Atlético Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (91, 'FC Bayern München', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (92, 'Atlético Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (93, 'FC Bayern München', 'Germany');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (94, 'FC Barcelona', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (95, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (96, 'Lazio', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (97, 'Inter', 'Italy');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (98, 'SL Benfica', 'Portugal');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (99, 'Real Madrid', 'Spain');
INSERT INTO Club (ClubID, ClubName, Country) VALUES (100, 'RC Celta', 'Spain');
