-- insert_nationality.sql

-- Ensure the table exists
CREATE TABLE IF NOT EXISTS Nationality (
    NationalityID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

-- Insert data into the Nationality table
INSERT INTO Nationality (NationalityID, Name) VALUES
(1, 'Argentina'),
(2, 'Portugal'),
(3, 'Brazil'),
(4, 'Netherlands'),
(5, 'Slovenia'),
(6, 'Belgium'),
(7, 'Poland'),
(8, 'Egypt'),
(9, 'Senegal'),
(10, 'Germany'),
(11, 'Spain'),
(12, 'France'),
(13, 'England'),
(14, 'Uruguay'),
(15, 'Croatia'),
(16, 'Italy'),
(17, 'Morocco'),
(18, 'Ivory Coast'),
(19, 'Cameroon'),
(20, 'Chile'),
(21, 'Mexico'),
(22, 'Colombia'),
(23, 'United States'),
(24, 'Canada'),
(25, 'Japan'),
(26, 'South Korea'),
(27, 'Turkey'),
(28, 'Russia'),
(29, 'Ukraine'),
(30, 'Norway'),
(31, 'Sweden'),
(32, 'Denmark'),
(33, 'Finland'),
(34, 'Serbia'),
(35, 'Bosnia & Herzegovina'),
(36, 'Switzerland'),
(37, 'Austria'),
(38, 'Hungary'),
(39, 'Romania'),
(40, 'Czech Republic'),
(41, 'Slovakia'),
(42, 'Greece'),
(43, 'Algeria'),
(44, 'Tunisia'),
(45, 'Gabon'),
(46, 'Nigeria'),
(47, 'Ghana'),
(48, 'Togo'),
(49, 'DR Congo'),
(50, 'South Africa'),
(51, 'Australia'),
(52, 'New Zealand'),
(53, 'China PR'),
(54, 'Saudi Arabia'),
(55, 'Iran'),
(56, 'Iraq'),
(57, 'Qatar'),
(58, 'United Arab Emirates'),
(59, 'Costa Rica'),
(60, 'Panama'),
(61, 'Paraguay'),
(62, 'Peru'),
(63, 'Venezuela'),
(64, 'Bolivia'),
(65, 'Ecuador'),
(66, 'Uruguay'),
(67, 'Honduras'),
(68, 'Guatemala'),
(69, 'El Salvador'),
(70, 'Trinidad & Tobago'),
(71, 'Jamaica'),
(72, 'Haiti'),
(73, 'Cuba'),
(74, 'Dominican Republic'),
(75, 'Puerto Rico'),
(76, 'Martinique'),
(77, 'Guadeloupe'),
(78, 'Saint Kitts and Nevis'),
(79, 'Saint Lucia'),
(80, 'Saint Vincent and the Grenadines'),
(81, 'Barbados'),
(82, 'Grenada'),
(83, 'Antigua and Barbuda'),
(84, 'Bahamas'),
(85, 'Bermuda'),
(86, 'Aruba'),
(87, 'Curaçao'),
(88, 'Suriname'),
(89, 'Guyana'),
(90, 'Belize'),
(91, 'Montserrat'),
(92, 'Anguilla'),
(93, 'British Virgin Islands'),
(94, 'Cayman Islands'),
(95, 'Turks and Caicos Islands'),
(96, 'Sint Maarten'),
(97, 'Saint Pierre and Miquelon'),
(98, 'Greenland'),
(99, 'Falkland Islands'),
(100, 'Gibraltar'),
(101, 'Faroe Islands'),
(102, 'San Marino'),
(103, 'Liechtenstein'),
(104, 'Andorra'),
(105, 'Monaco'),
(106, 'Vatican City'),
(107, 'Kosovo'),
(108, 'Palestine'),
(109, 'Syria'),
(110, 'Lebanon'),
(111, 'Jordan'),
(112, 'Kuwait'),
(113, 'Bahrain'),
(114, 'Oman'),
(115, 'Yemen'),
(116, 'Afghanistan'),
(117, 'Pakistan'),
(118, 'India'),
(119, 'Bangladesh'),
(120, 'Sri Lanka'),
(121, 'Nepal'),
(122, 'Bhutan'),
(123, 'Maldives'),
(124, 'Myanmar'),
(125, 'Thailand'),
(126, 'Vietnam'),
(127, 'Cambodia'),
(128, 'Laos'),
(129, 'Malaysia'),
(130, 'Singapore'),
(131, 'Brunei'),
(132, 'Philippines'),
(133, 'Indonesia'),
(134, 'Timor-Leste'),
(135, 'Papua New Guinea'),
(136, 'Solomon Islands'),
(137, 'Vanuatu'),
(138, 'Fiji'),
(139, 'Tonga'),
(140, 'Samoa'),
(141, 'American Samoa'),
(142, 'Cook Islands'),
(143, 'Niue'),
(144, 'Tokelau'),
(145, 'Tuvalu'),
(146, 'Nauru'),
(147, 'Kiribati'),
(148, 'Marshall Islands'),
(149, 'Palau'),
(150, 'Micronesia'),
(151, 'Northern Mariana Islands'),
(152, 'Guam'),
(153, 'Wake Island'),
(154, 'Midway Atoll'),
(155, 'Baker Island'),
(156, 'Howland Island'),
(157, 'Jarvis Island'),
(158, 'Kingman Reef'),
(159, 'Johnston Atoll'),
(160, 'Navassa Island'),
(161, 'Serranilla Bank'),
(162, 'Bajo Nuevo Bank'),
(163, 'Clipperton Island'),
(164, 'Ashmore and Cartier Islands'),
(165, 'Coral Sea Islands'),
(166, 'Norfolk Island'),
(167, 'Christmas Island'),
(168, 'Cocos (Keeling) Islands'),
(169, 'Pitcairn Islands'),
(170, 'French Polynesia'),
(171, 'New Caledonia'),
(172, 'Wallis and Futuna'),
(173, 'Saint Barthelemy'),
(174, 'Saint Martin'),
(175, 'Saint Helena'),
(176, 'Ascension Island'),
(177, 'Tristan da Cunha'),
(178, 'South Georgia and the South Sandwich Islands'),
(179, 'British Indian Ocean Territory'),
(180, 'Diego Garcia'),
(181, 'Chagos Archipelago'),
(182, 'Heard Island and McDonald Islands'),
(183, 'Bouvet Island'),
(184, 'South Orkney Islands'),
(185, 'South Shetland Islands'),
(186, 'Antarctica'),
(187, 'Ross Dependency'),
(188, 'Australian Antarctic Territory'),
(189, 'Argentine Antarctica'),
(190, 'Chilean Antarctic Territory'),
(191, 'British Antarctic Territory'),
(192, 'New Zealand Antarctic Territory'),
(193, 'Norwegian Antarctic Territory'),
(194, 'French Southern and Antarctic Lands'),
(195, 'United States Antarctic Territory'),
(196, 'Russian Antarctic Territory'),
(197, 'Indian Antarctic Territory'),
(198, 'Chinese Antarctic Territory'),
(199, 'Japanese Antarctic Territory'),
(200, 'South African Antarctic Territory'),
(201, 'Brazilian Antarctic Territory'),
(202, 'Uruguayan Antarctic Territory'),
(203, 'Peruvian Antarctic Territory'),
(204, 'Ecuadorian Antarctic Territory'),
(205, 'Colombian Antarctic Territory'),
(206, 'Venezuelan Antarctic Territory'),
(207, 'Panamanian Antarctic Territory'),
(208, 'Costa Rican Antarctic Territory'),
(209, 'Guatemalan Antarctic Territory'),
(210, 'Honduran Antarctic Territory'),
(211, 'Salvadoran Antarctic Territory'),
(212, 'Nicaraguan Antarctic Territory'),
(213, 'Belizean Antarctic Territory'),
(214, 'Mexican Antarctic Territory'),
(215, 'Cuban Antarctic Territory'),
(216, 'Haitian Antarctic Territory'),
(217, 'Dominican Antarctic Territory'),
(218, 'Puerto Rican Antarctic Territory'),
(219, 'Saint Lucian Antarctic Territory'),
(220, 'Saint Vincentian Antarctic Territory'),
(221, 'Barbadian Antarctic Territory'),
(222, 'Grenadian Antarctic Territory'),
(223, 'Antiguan Antarctic Territory'),
(224, 'Bahaman Antarctic Territory'),
(225, 'Bermudan Antarctic Territory'),
(226, 'Aruban Antarctic Territory'),
(227, 'Curaçaoan Antarctic Territory'),
(228, 'Surinamese Antarctic Territory'),
(229, 'Guyanan Antarctic Territory'),
(230, 'Belizean Antarctic Territory'),
(231, 'Montserratian Antarctic Territory'),
(232, 'Anguillan Antarctic Territory'),
(233, 'British Virgin Islands Antarctic Territory'),
(234, 'Cayman Islands Antarctic Territory'),
(235, 'Turks and Caicos Islands Antarctic Territory'),
(236, 'Sint Maarten Antarctic Territory'),
(237, 'Saint Pierre and Miquelon Antarctic Territory'),
(238, 'Greenland Antarctic Territory'),
(239, 'Falkland Islands Antarctic Territory'),
(240, 'Gibraltar Antarctic Territory'),
(241, 'Faroe Islands Antarctic Territory'),
(242, 'San Marino Antarctic Territory'),
(243, 'Liechtenstein Antarctic Territory'),
(244, 'Andorra Antarctic Territory'),
