INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (158023, 'Lionel Messi', 1, 1, 94);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (20801, 'Cristiano Ronaldo', 2, 2, 93);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (190871, 'Neymar Jr', 3, 3, 92);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (203376, 'Virgil van Dijk', 4, 4, 91);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (200389, 'Jan Oblak', 5, 5, 91);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (192985, 'Kevin De Bruyne', 6, 6, 91);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (188545, 'Robert Lewandowski', 7, 7, 91);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (183277, 'Eden Hazard', 8, 8, 91);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (212831, 'Alisson', 9, 9, 90);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (209331, 'Mohamed Salah', 10, 10, 90);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (208722, 'Sadio Mané', 11, 11, 90);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (192448, 'Marc-André ter Stegen', 12, 12, 90);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (153079, 'Sergio Agüero', 13, 13, 90);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (231747, 'Kylian Mbappé', 14, 14, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (215914, 'NGolo Kanté', 15, 15, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (202126, 'Harry Kane', 16, 16, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (194765, 'Antoine Griezmann', 17, 17, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (182521, 'Toni Kroos', 18, 18, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (177003, 'Luka Modric', 19, 19, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (176580, 'Luis Suárez', 20, 20, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (167495, 'Manuel Neuer', 21, 21, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (155862, 'Sergio Ramos', 22, 22, 89);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (210257, 'Ederson', 23, 23, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (202652, 'Raheem Sterling', 24, 24, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (201942, 'Roberto Firmino', 25, 25, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (201024, 'Kalidou Koulibaly', 26, 26, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (200145, 'Casemiro', 27, 27, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (193080, 'De Gea', 28, 28, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (192119, 'Thibaut Courtois', 29, 29, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (189511, 'Sergio Busquets', 30, 30, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (188567, 'Pierre-Emerick Aubameyang', 31, 31, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (165153, 'Karim Benzema', 32, 32, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (162835, 'Samir Handanovic', 33, 33, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (152729, 'Piqué', 34, 34, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (138956, 'Giorgio Chiellini', 35, 35, 88);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (218667, 'Bernardo Silva', 36, 36, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (212622, 'Joshua Kimmich', 37, 37, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (212218, 'Aymeric Laporte', 38, 38, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (211110, 'Paulo Dybala', 39, 39, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (200104, 'Heung Min Son', 40, 40, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (199556, 'Marco Verratti', 41, 41, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (195864, 'Paul Pogba', 42, 42, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (193041, 'Keylor Navas', 43, 43, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (192387, 'Ciro Immobile', 44, 44, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (190460, 'Christian Eriksen', 45, 45, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (189513, 'Parejo', 46, 46, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (188350, 'Marco Reus', 47, 47, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (186153, 'Wojciech Szczesny', 48, 48, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (183898, 'Ángel Di María', 49, 49, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (182493, 'Diego Godín', 50, 50, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (178603, 'Mats Hummels', 51, 51, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (175943, 'Dries Mertens', 52, 52, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (168542, 'David Silva', 53, 53, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (167948, 'Hugo Lloris', 54, 54, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (164240, 'Thiago Silva', 55, 55, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (233049, 'Jadon Sancho', 1, 1, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (232363, 'Milan Škriniar', 2, 2, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (228702, 'Frenkie de Jong', 3, 3, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (222492, 'Leroy Sané', 4, 4, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (220440, 'Clément Lenglet', 5, 5, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (216267, 'Andrew Robertson', 6, 6, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (212198, 'Bruno Fernandes', 7, 7, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (212188, 'Timo Werner', 8, 8, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (209499, 'Fabinho', 9, 9, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (208830, 'Jamie Vardy', 10, 10, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (208670, 'Hakim Ziyech', 11, 11, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (207865, 'Marquinhos', 12, 12, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (204485, 'Riyad Mahrez', 13, 13, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (201535, 'Raphaël Varane', 14, 14, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (201399, 'Mauro Icardi', 15, 15, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (198219, 'Lorenzo Insigne', 16, 16, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (193747, 'Koke', 17, 17, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (192505, 'Romelu Lukaku', 18, 18, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (189509, 'Thiago', 19, 19, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (189332, 'Jordi Alba', 20, 20, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (184344, 'Leonardo Bonucci', 21, 21, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (184087, 'Toby Alderweireld', 22, 22, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (180206, 'Miralem Pjanic', 23, 23, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (179813, 'Edinson Cavani', 24, 24, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (177683, 'Yann Sommer', 25, 25, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (143076, 'Alejandro Gómez', 26, 26, 87);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (235243, 'Matthijs de Ligt', 27, 27, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (231866, 'Rodri', 28, 28, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (231281, 'Trent Alexander-Arnold', 29, 29, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (230658, 'Arthur', 30, 30, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (230621, 'Gianluigi Donnarumma', 31, 31, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (226753, 'André Onana', 32, 32, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (223848, 'Sergej Milinkovic-Savic', 33, 33, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (216594, 'Nabil Fekir', 34, 34, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (216460, 'José María Giménez', 35, 35, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (212190, 'Niklas Süle', 36, 36, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (208421, 'Saúl', 37, 37, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (206113, 'Serge Gnabry', 38, 38, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (205600, 'Samuel Umtiti', 39, 39, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (204963, 'Carvajal', 40, 40, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (198706, 'Luis Alberto', 41, 41, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (198176, 'Stefan de Vrij', 42, 42, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (197965, 'Pizzi', 43, 43, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (197781, 'Isco', 44, 44, 85);
INSERT INTO Player (PlayerID, Name, NationalityID, PositionID, OverallRating) VALUES (192629, 'Iago Aspas', 45, 45, 85);



